### PR TITLE
Add Models Folder

### PR DESCRIPTION
**Pull request by tmcdon89**
Side Note - Accidentally added the packages controller in this commit.

### CODE REVIEW

**Comment by turtles2** [comment]
In my last commit I added a new model and controller. Could you update those as well to using the models folder before I pull this in?

**Comment by tmcdon89** [comment]
Alright I added them in.

**Comment by turtles2** [comment]
FYI you did not update Relationships in the models I did and pushed it up so make sure you add those to your repo

**Comment by tmcdon89** [comment]
Will do, thanks.

**Pull request merged**
