### PR TITLE
Initial Submission

### PR DESCRIPTION
**Pull request by tmcdon89**
This is a scrubbed version of what we currently use. Its possible I broke some functionality while cleaning out company specific files. I tested some to make sure the general functionality was there but that's as far as I've currently gotten. 
This should at least give a baseline to start with even if we scrap a lot of it.
Additionally I removed files deemed unnecessary via issue:  #1

### CODE REVIEW

**Comment by turtles2** [comment]
This was not quite what I had in mind. I was thinking we would make small incremental changes using your completed code along with the addition of new code. I was opening to have a somewhat clean slate for everybody.

I will pull this down and tinker but I feel a cleaner slate might be better. 

Also some files were removed that I thought were going to stay in place like .gitignore

**Comment by turtles2** [comment]
To follow up I wanted to mention that the master branch right now is not a clean laravel install there is a n admin template in there that I am quite used as I have used in a few projects incuding the non laravel WISPBill

**Comment by tmcdon89** [comment]
No need to commit this pull as is. I was just trying to throw up a quick way for you to take a look at what I've currently got thats laravel based. Quite a bit should be looked at. For example I don't think many of the migrations and equipment options are necessary at this time, if at all. 
I can close out and let you check it out from my fork if you prefer.

**Comment by turtles2** [comment]
Got I feel that this pull won't be committed as is. My personal style which I would like this project to follow is small incremental commits. For example if you made a delete and create users changes you would make a pull for each. That way pulls are kept on a certain focus.

**Comment by tmcdon89** [comment]
I'll leave my fork up for you to poke through. once you get some commits up I'll have a better feel for how to contribute.

**Pull request closed without merging**
